name: Test new branches or changes

on:
  push:

jobs:
  # джоба, которая устанавливает nodejs, npm, зависимости, тестирует код и собирает клиента
  test_branches:
    runs-on: ubuntu-20.04
    steps:
      # Чекаутим код
      - uses: actions/checkout@v2
      - name: Install Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 19.x
      - name: Install dependencies for the server and client side
        run: npm i && npm run client:install
      - name: run all tests
        run: npm run client:test
      - name: build the client side
        run: npm run client:build